server:
  port: 8087
spring:
  servlet:
    multipart:
      max-file-size: 10MB
fdfs:
  soTimeout: 5000
  connectTimeout: 6000
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:
    - 172.16.0.199:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 30
    min-idle-per-key: 20
    test-on-borrow: true